FROM node:slim

#COPY ./frontend /ui
WORKDIR /usr/src/packages

COPY frontend/package.json frontend/yarn.loc[k] ./

#COPY ./frontend 
#WORKDIR /ui


expose 5173

RUN yarn install

COPY ./frontend .
RUN yarn build  # If you want to build the dist instead
CMD yarn
CMD yarn dev
